### ISSUE TITLE
Документация по сборке в pdf

### ISSUE THREAD

**Issue by a7emenov** [aolo2/IU9-Mathmod#1]
Было бы неплохо, если в Readme проекта была полная инструкция по сборке `tex -> pdf`, начиная с установки необходимых зависимостей. На текущий момент единственный способ, который мне известен, это скачать 3 гб зависимостей пакета `textlive-full`.

**Comment by aolo2** [comment]
Добавил актуальный ```pdf``` в репозиторий

\- aolo2
