### ISSUE TITLE
Включите GitHub Pages для репозитория

### ISSUE THREAD

**Issue by Mazdaywik** [aolo2/IU9-Mathmod#2]
Если включите в настройках GitHub Pages, то лекции можно будет скачать по прямой ссылке <https://aolo2.github.io/IU9-Mathmod/mathmod.pdf>. Можно добавить `README.md`, который будет отображаться по ссылке <https://aolo2.github.io/IU9-Mathmod>.

**Comment by aolo2** [comment]
Сделал, спасибо!

\- aolo2

**Comment by Mazdaywik** [comment]
Можно добавить ссылку на pdf в описание репозитория. Можно добавить README.md с таким содержимым:
```Markdown
[Читать конспект лекций](mathmod.pdf)
```
